#!/bin/bash

#SBATCH --job-name=Convnet

#SBATCH --time=1:00:00

module load 2019
module load eb

module load pre2019
module load Python/3.6.3-foss-2017b
module load cuDNN/7.0.5-CUDA-9.0.176
module load NCCL/2.0.5-CUDA-9.0.176
export LD_LIBRARY_PATH=/hpc/eb/Debian9/cuDNN/7.1-CUDA-8.0.44-GCCcore-5.4.0/lib64:$LD_LIBRARY_PATH

module load CUDA/10.0.130
module load Anaconda3/2018.12

source activate dl

srun python3 -u train_convnet_pytorch.py > convnet.out








